// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetWebsocketUrl():Promise<string>;

export function Quit():Promise<void>;

export function SetPtySize(arg1:number,arg2:number):Promise<void>;
