// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetPlatform():Promise<main.Platform>;

export function GetTerminalFontConfig():Promise<main.TerminalFontConfig>;

export function GetTerminalTheme():Promise<main.TerminalTheme>;

export function GetWebsocketUrl():Promise<string>;

export function Quit():Promise<void>;

export function SetPtySize(arg1:number,arg2:number):Promise<void>;
