// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetTerminalFontConfig() {
  return window['go']['main']['App']['GetTerminalFontConfig']();
}

export function GetTerminalTheme() {
  return window['go']['main']['App']['GetTerminalTheme']();
}

export function GetWebsocketUrl() {
  return window['go']['main']['App']['GetWebsocketUrl']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SetPtySize(arg1, arg2) {
  return window['go']['main']['App']['SetPtySize'](arg1, arg2);
}
